# Generated by Django 4.2.17 on 2026-01-29 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('image_hash', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('google', 'Google Drive')], max_length=20)),
                ('category_main', models.CharField(default='기타', max_length=50)),
                ('category_sub', models.CharField(blank=True, max_length=50, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('memo', models.TextField(blank=True, null=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('is_trashed', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('notif_type', models.CharField(choices=[('reminder', '리마인드'), ('trash', '휴지통이동')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
