# Generated by Django 4.2.17 on 2026-02-13 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reminder_enabled', models.BooleanField(default=True)),
                ('reminder_days', models.IntegerField(default=7)),
                ('is_auto_trash_enabled', models.BooleanField(default=False)),
                ('auto_trash_days', models.IntegerField(default=30)),
                ('trash_expiry_days', models.IntegerField(default=30)),
                ('auto_trash_categories', models.ManyToManyField(blank=True, related_name='trash_settings', to='gallery.category')),
                ('reminder_categories', models.ManyToManyField(blank=True, to='gallery.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
