# Generated by Django 4.2.17 on 2026-01-30 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category_main',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='category_sub',
        ),
        migrations.AddField(
            model_name='notification',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='gallery.photo'),
        ),
        migrations.AddField(
            model_name='notification',
            name='remind_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category_key', models.CharField(blank=True, choices=[('finance', '결제/금융'), ('study_note', '학습/노트'), ('shopping', '쇼핑 정보'), ('schedule', '일정/예약'), ('document', '문서/정보'), ('others', '기타정보(비정보)')], max_length=20, null=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='gallery.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='gallery.category'),
        ),
    ]
