# Generated by Django 4.2.17 on 2026-02-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_usersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_key',
            field=models.CharField(blank=True, choices=[('finance', '결제/예약'), ('study_note', '학습/노트'), ('info', '정보'), ('others', '기타')], max_length=20, null=True),
        ),
    ]
