# Generated by Django 4.2.11 on 2026-01-30 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Exact duplicate인 경우, 원본 Photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='photos.photo'),
        ),
    ]
