# Generated by Django 4.2.17 on 2026-02-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_duplicate_of'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
